# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
cmd-alt-enter = '''exec-and-forget osascript -e '
tell application "Terminal"
    do script
    activate
end tell'
'''

# i3 wraps focus by default
cmd-j = 'focus --boundaries-action wrap-around-the-workspace down'
cmd-k = 'focus --boundaries-action wrap-around-the-workspace up'
cmd-l = 'focus --boundaries-action wrap-around-the-workspace right'
cmd-h = 'focus --boundaries-action wrap-around-the-workspace left'

shift-alt-j = 'move down'
shift-alt-k = 'move up'
shift-alt-l = 'move right'
shift-alt-h = 'move left'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
shift-alt-s = 'split horizontal'
shift-alt-v = 'split vertical'

cmd-alt-f = 'fullscreen'

cmd-alt-s = 'layout v_accordion'               # 'layout stacking' in i3
cmd-alt-w = 'layout h_accordion'               # 'layout tabbed' in i3
cmd-alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

shift-alt-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

cmd-alt-1 = 'workspace 1'
cmd-alt-2 = 'workspace 2'
cmd-alt-3 = 'workspace 3'
cmd-alt-4 = 'workspace 4'
cmd-alt-5 = 'workspace 5'
cmd-alt-6 = 'workspace 6'
cmd-alt-7 = 'workspace 7'
cmd-alt-8 = 'workspace 8'
cmd-alt-9 = 'workspace 9'
cmd-alt-0 = 'workspace 10'

shift-alt-1 = 'move-node-to-workspace 1'
shift-alt-2 = 'move-node-to-workspace 2'
shift-alt-3 = 'move-node-to-workspace 3'
shift-alt-4 = 'move-node-to-workspace 4'
shift-alt-5 = 'move-node-to-workspace 5'
shift-alt-6 = 'move-node-to-workspace 6'
shift-alt-7 = 'move-node-to-workspace 7'
shift-alt-8 = 'move-node-to-workspace 8'
shift-alt-9 = 'move-node-to-workspace 9'
shift-alt-0 = 'move-node-to-workspace 10'

shift-alt-c = 'reload-config'

cmd-alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
k = 'resize height +50'
j = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10
