ln -s ~/dotfiles/nvim ~/.config/nvim
ln -s ~/dotfiles/yazi ~/.config/yazi
ln -s ~/dotfiles/.zshrc-mac ~/.zshrc
ln -s ~/dotfiles/starship.toml ~/.config/starship.toml
ln -s ~/dotfiles/kitty ~/.config/kitty
ln -s ~/dotfiles/alacritty ~/.config/alacritty
ln -s ~/dotfiles/skhd ~/.config/skhd
ln -s ~/dotfiles/yabai ~/.config/yabai
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
